line-length = 120
target-version = 'py313'
fix = true
include = [
    "conftest/**/*.py",
    "app/**/*.py",
    "tests/**/*.py"
]

[lint]
select = ["I", "PL", "F401", "F841", "N", "R", "E501"]
ignore = []

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]